spring:
  application:
    name: storage
  mvc:
    servlet:
      path: /storage

application:
  bucket:
    name: hr-project-file-storage

server:
  port: 8007

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka