spring:
  application:
    name: onboard
  mvc:
    servlet:
      path: /onboard

server:
  port: 8006

security:
  jwt:
    token:
      key: HRProject

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka