spring:
  application:
    name: hr
  mvc:
    servlet:
      path: /hr

server:
  port: 8005

security:
  jwt:
    token:
      key: HRProject

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
