spring:
  application:
    name: housing
  mvc:
    servlet:
      path: /housing

server:
  port: 8003

database:
  hibernate:
    url: jdbc:mysql://hr-project.cm17bivyf0ej.us-east-1.rds.amazonaws.com:3306/HousingService
    driver: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin123
    dialect: org.hibernate.dialect.MySQL5Dialect
    showsql: true
    hbm2ddl:
      auto: update

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
